version_id:
  type: string
  in: body
  required: true
  description: >
    A common name for the version being described. Informative only.
version_max:
  type: string
  in: body
  required: true
  description: >
    The maximum microversion that is supported.
version_min:
  type: string
  in: body
  required: true
  description: >
    The minimum microversion that is supported.
versions:
  type: array
  in: body
  required: true
  description: >
    A list of version objects that describe the API versions available.
